name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            arch: x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"
      # Cache Cargo builds
      - name: Cache Cargo build artifacts
        uses: actions/cache@v3
        with:
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
      - uses: dtolnay/rust-toolchain@1.79
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
      - name: Compress binary
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            tar -czvf holochain-runner-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release holochain-runner.exe
          else
            tar -czvf holochain-runner-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release holochain-runner
          fi
      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: holochain-runner-${{ matrix.target }}.tar.gz
          path: holochain-runner-${{ matrix.target }}.tar.gz
