name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      releaseId: ${{ steps.step1.outputs.id }}
    steps:
      - id: step1
        uses: ncipollo/release-action@v1
        with:
          name: "holochain-runner ${{ github.ref_name }}"
          body: ""
          prerelease: true
          draft: true

  build:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc
          - os: macos-13
            arch: x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"
      # Cache Cargo builds
      - name: Cache Cargo build artifacts
        uses: actions/cache@v3
        with:
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
      - uses: dtolnay/rust-toolchain@1.79
      - name: Check if cache was restored
        id: cache-check
        run: |
          if [ -d "target/${{ matrix.target }}/release" ]; then
            echo "cache-hit=true" >> $GITHUB_ENV
            echo "::set-output name=cache-hit::true"
          else
            echo "cache-hit=false" >> $GITHUB_ENV
            echo "::set-output name=cache-hit::false"
          fi
        shell: bash
      - name: Build binary
        if: steps.cache-check.outputs.cache-hit == 'false'
        run: cargo build --release --target ${{ matrix.target }}
      - name: Compress binary
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            tar -czvf holochain-runner-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release holochain-runner.exe
          else
            tar -czvf holochain-runner-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release holochain-runner
          fi
        shell: bash
      - name: Upload Release Asset
        uses: AButler/upload-release-assets@v3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-id: ${{ needs.create-release.outputs.releaseId }}
          files: holochain-runner-${{ matrix.target }}.tar.gz
